name: Build artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_everything:
    name: Build everything
    runs-on: ubuntu-latest
    steps:
    - name: Do checkout (whatever that means)
      uses: actions/checkout@v3
    - name: Setup JRE
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Set execution permission for gradlew
      run: chmod +x gradlew
    - name: Build debug APK, desktop lwjgl2 and lwjgl3 dist
      run: |
        ./gradlew android:assembleDebug
        ./gradlew desktop:dist
        ./gradlew desktopLwjgl3:dist
    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: android/build/outputs/apk/debug/android-debug.apk
    - name: Upload lwjgl2 dist
      uses: actions/upload-artifact@v3
      with:
        name: app-desktopLwjgl2.jar
        path: desktop/build/libs/desktop-1.0.jar
    - name: Upload lwjgl3 dist
      uses: actions/upload-artifact@v3
      with:
        name: app-desktopLwjgl3.jar
        path: desktopLwjgl3/build/libs/desktopLwjgl3-1.0.jar
