name: Build_artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_everything:
    name: Build everything
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 11
    - name: Build debug APK, desktop lwjgl2 dist and desktop lwjgl3 dist
      run: |
        ./gradlew android:assembleDebug
        ./gradlew desktop:dist
        ./gradlew desktopLwjgl3:dist
    - name: Upload debug APK
      uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: android/build/outputs/apk/debug/android-debug.apk
    - name: Upload desktop lwjgl2 dist
      uses: actions/upload-artifact@v2
      with:
        name: app-desktopLwjgl2.jar
        path: desktop/build/libs/desktop-1.0.jar
    - name: Upload desktop lwjgl2 dist
      uses: actions/upload-artifact@v2
      with:
        name: app-desktopLwjgl3.jar
        path: desktopLwjgl3/build/libs/desktopLwjgl3-1.0.jar
